name: Run Coverage and UnitTest
on: 
  pull_request:
    branches: 
      - main 
    paths:
      - src/tfcloud_sdk/**
      - tests/**
      - "**.py"
      - pyproject.toml

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Requirements
        run: |
          sudo apt install python3 python3-pip pipenv
          pipenv run install -d 

      - name: Run UnitTest
        run: |
          pipenv run coverage run -m unittest discover

      - name: Output Report 
        run: |
          pipenv run coverage report >> $GITHUB_STEP_SUMMARY
