name: Deploys Package to PyPi 
on: 
  push:
    branches:
      - main 
    paths: 
      - src/tfcloud_sdk/**
      - tests/**
      - "**.py"

jobs: 
  extract_version:
    runs-on: ubuntu-latest
    outputs: 
      package_version: ${{ steps.versions.outputs.package_version }}
      python_version: ${{ steps.versions.outputs.python_version }}
    steps:

      - name: Checkout Repository
        uses: actions@checkout/v4

      - name: Extract Versions
        id: versions
        run: |  
          echo package_version=$(grep 'version' pyproject.toml | cut -d'"' -f2) >> $GITHUB_OUTPUTS
          echo python_version=$(grep 'requires-python' pyproject.toml | cut -d'"' -f2 | cut -d '=' -f2) >> $GITHUB_OUTPUTS

  deploy_package:
    needs: extract_version
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tfcloud_sdk
    steps:

      - name: Checkout Repository
        uses: actions@checkout/v4

      - name: Setup Python 
        uses: actions/setup-python@v4
        with:
          python-version: ${{ jobs.extract_version.outputs.python_version }}

      - name: Install Dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install setuptools 

      - name: Build Package 
        run: |
          python -m build 

      - name: Publish Package to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1

  register_release:
    runs-on: ubuntu-latest
    needs: 
      - extract_version
      - deploy_package
    steps:

      - name: Create a Release in a GitHub Action
        uses: comnoco/create-release-action@v2.0.5
        with: 
          tag_name: v${{ steps.versions.outputs.package_version }}
          release_name: v${{ steps.versions.outputs.package_version }}
          